language: shell
os: linux
dist: bionic

services:
  - docker

env:
  - TAG=hirsute
  - TAG=groovy
  - TAG=focal
  - TAG=bionic

script:
  - docker build -t $DOCKER_REPO:ubuntu-$TAG --build-arg TAG=$TAG .

deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = cron
